NorthernTechHQ/nt-gui

.github/dependabot.yml
.github/workflows/storybook.yml
.gitlab-ci.yml
package-lock.json
package.json
release-please-config.json

@oldgiova based on https://gitlab.com/Northern.tech/northerntechhq/nt-gui/-/jobs/8176603280#L199 I would have expected this to fail in Mender too?

Fix/pages deploy+dependabot config

---

release-please-config.json

- configuring a path seems to no longer be supported

fix: also adjusted package references in release-please config

---

.gitlab-ci.yml

Missing the output flag
Ticket: None
Changelog: None

ci: fix git cliff command

---

.gitignore
.gitlab-ci.yml

Edit the Changelog and the body PR for the bundle version, plus the changelog for each component.

ci: use git cliff on subcomponents

---

packages/store/organizationSlice/index.ts
packages/store/organizationSlice/thunks.ts
packages/utils/liststatehook.js
packages/utils/locationutils.js

Ticket: MEN-7658
Changelog: None

feat: added tenant-related location utils

---

turbo.json

remove ^ in dependsOn to enforce task order within the same package

chore: remove ^ from dependsOn tasks in turbo.json

---

.gitlab-ci.yml

to address [this](https://gitlab.com/Northern.tech/northerntechhq/nt-gui/-/jobs/8322929702)

fix: avoided failing bash multiline interpretation

---

.gitlab-ci.yml

Added tag-pattern option

---

.gitlab-ci.yml

chore: add debug step

---

.gitlab-ci.yml

ci: refactor loop query

---

.gitlab-ci.yml

ci: added debug checks

---

.gitlab-ci.yml

for Release please
Depends on: https://github.com/mendersoftware/mender-test-containers/pull/625

ci: move to pre-baked base images

---

packages/store/package.json

Added rules for types and slices

fix: fixed store package export

---

.gitlab-ci.yml

ci: fix unused variable

---

packages/common-ui/src/forms/TimeframePicker.tsx
packages/common-ui/src/forms/__snapshots__/TimeFramePicker.test.tsx.snap

Ticket: MEN-7855
Changelog: None

fix: reverted changes to timeframe picker used in CFEnigne MP

---

packages/utils/src/helpers.ts

the lint rules lost the race between the previous PRs 🙈

chore: fixed linter issues

---

packages/utils/src/helpers.test.ts
packages/utils/src/helpers.ts

ChangeLog: Title
Ticket: MEN-8150

fix(utils): fixed dateRangeToUnix function where start date was off by -1 day in some cases

---

packages/store/src/usersSlice/thunks.test.ts
tests/__mocks__/userHandlers.js

Ticket: QA-984
Changelog: None

test: made password changing msw rely on current password

---

packages/store/src/appSlice/index.ts
packages/store/src/storehooks.ts
packages/store/src/utils.test.ts
packages/store/src/utils.ts

fix(store): aligned store w/ mender to remove demo features

---

packages/common/src/theme-explorer/MuiComponents.stories.tsx

see https://nt-gui-e21511.gitlab.io/pr-353/?path=/story/common-themeexplorer-allcomponents--all-components

feat(common): added mui component overview to ease seeing theme impact
